---
name: Docker Image CI
on:
  workflow_run:
    workflows:
      - NodeJS with Grunt
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: diagram.zip
      - name: list files
        run: ls -lah
        shell: bash
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ts-github-actions:$(date +%s)
