---
name: Docker Image CI
on:
  workflow_run:
    workflows:
      - NodeJS with Grunt
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ts-github-actions:$(date +%s)
